apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus

resources:
  - ../../base

images:
  - name: nexus3-gcs
    newName: REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/nexus3-gcs
    newTag: "3.68.1"   # kunci ke versi yang sudah terbukti jalan
